title: working-as-designed
description: This is my blog. There are many like it, but this one is mine.
baseurl: ""
url: "https://working-as-designed.github.io"
remote-theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag

tag_page_layout: custom-tag
tag_page_dir: tags
tag_permalink_style: pretty

# Enable sidebar globally
sidebar:
  enabled: true
  nav: "main"     # Refers to _data/navigation.yml

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        enabled: true
        nav: main
        custom: custom-sidebar
